/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import views.RegionView;

/**
 *
 * @author Yosef Febrianes
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jobsButton = new javax.swing.JButton();
        jobHistoryButton = new javax.swing.JButton();
        contriesButton = new javax.swing.JButton();
        regionButton = new javax.swing.JButton();
        departementsButton = new javax.swing.JButton();
        employeesButton = new javax.swing.JButton();
        locationsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jobsButton.setText("JOBS");
        getContentPane().add(jobsButton);
        jobsButton.setBounds(1110, 350, 130, 50);

        jobHistoryButton.setText("JOB_HISTORY");
        getContentPane().add(jobHistoryButton);
        jobHistoryButton.setBounds(1110, 430, 130, 50);

        contriesButton.setText("CONTRIES");
        getContentPane().add(contriesButton);
        contriesButton.setBounds(1110, 110, 130, 50);

        regionButton.setText("REGIONS");
        regionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regionButton);
        regionButton.setBounds(1110, 590, 130, 50);

        departementsButton.setText("DEPARTEMENTS");
        departementsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departementsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departementsButton);
        departementsButton.setBounds(1110, 190, 130, 50);

        employeesButton.setText("EMPLOYEES");
        employeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(employeesButton);
        employeesButton.setBounds(1110, 270, 130, 50);

        locationsButton.setText("LOCATIONS");
        locationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(locationsButton);
        locationsButton.setBounds(1110, 510, 130, 50);

        jLabel2.setBackground(new java.awt.Color(255, 255, 51));
        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("tugas akhir pekan KP_UKSW_Batch2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 460, 600, 160);

        jLabel3.setBackground(new java.awt.Color(255, 255, 51));
        jLabel3.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PT. Metrodata Electronics, Tbk");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 570, 870, 160);

        jLabel4.setBackground(new java.awt.Color(255, 255, 51));
        jLabel4.setFont(new java.awt.Font("Courier New", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The Human Resources Schema");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 30, 940, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yosef Febrianes\\Documents\\NetBeansProjects\\TugasAkhirPekan\\src\\W1.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departementsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departementsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departementsButtonActionPerformed

    private void regionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionButtonActionPerformed
        // TODO add your handling code here:
        RegionView rv = new RegionView();
        rv.setVisible(true);
    }//GEN-LAST:event_regionButtonActionPerformed

    private void locationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationsButtonActionPerformed
        // TODO add your handling code here:
        LocationView lv = new LocationView();
        lv.setVisible(true);
    }//GEN-LAST:event_locationsButtonActionPerformed

    private void employeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesButtonActionPerformed
        // TODO add your handling code here:
        EmployeeView ev = new EmployeeView();
        ev.setVisible(true);
    }//GEN-LAST:event_employeesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contriesButton;
    private javax.swing.JButton departementsButton;
    private javax.swing.JButton employeesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jobHistoryButton;
    private javax.swing.JButton jobsButton;
    private javax.swing.JButton locationsButton;
    private javax.swing.JButton regionButton;
    // End of variables declaration//GEN-END:variables
}
