/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.mysql.jdbc.Connection;
import controllers.DepartmentsControllers;
import controllers.icontrollers.IDepartmentsControllers;
import daos.DepartmentDao;
import daos.EmployeeDao;
import daos.idaos.IEmployeeDao;
import javax.swing.DefaultButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.Department;
import tools.DbConnection;
import daos.idaos.IDepartmentDao;

/**
 *
 * @author User
 */
public class DepartmentView extends javax.swing.JFrame {
    static JScrollPane scroll = new JScrollPane();   
    DefaultTableModel model;
    
    public DepartmentView() {
        initComponents();
        showtable();
    }
    
    void showtable(){
        DbConnection connection = new DbConnection();
        IDepartmentDao iddao = new DepartmentDao((Connection) connection.getConnection());
        
        DefaultTableModel dftm;
        DefaultButtonModel dfbm;

        Object[] baris = {"Department ID", "Department Name", "Manager ID", "Location ID"};
        dftm = new DefaultTableModel(null, baris);
        tabeldepartment.setModel(dftm);
        
        txt_deparmentID.setText("");
        txt_departmentName.setText("");
        txt_managerID.setText("");
        txt_locationID.setText("");

        try {
            for (Department depgoin : iddao.getAll()) {

                String depID = depgoin.getDepartmentID();
                String depNM = depgoin.getDepartmentName();
                String depManID = depgoin.getManagerID();
                String depLocID = depgoin.getLocationID();

                String[] data = {depID, depNM, depManID, depLocID};
                dftm.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something was wrong!\n" + e, "Error"
                    , JOptionPane.ERROR_MESSAGE);

        }
    }
    
    private void searching() {
        DbConnection connection = new DbConnection();
        IDepartmentDao idepdao = new DepartmentDao(connection.getConnection());
        IDepartmentsControllers idc = new DepartmentsControllers(connection.getConnection());
        Department departments = new Department(btn_search.getText());

//        Region r = new Region();
        DefaultTableModel dt;
        DefaultButtonModel db;

        Object[] baris = {"Department ID", "Department Name", "Manager ID", "Location ID"};
        dt = new DefaultTableModel(null, baris);
        tabeldepartment.setModel(dt);

        try {
            for (Department depgoin : idepdao.search(txt_search.getText())) {
//                System.out.println(regiong.getRegionId() + " || " + regiong.getRegionName());

                String ID = depgoin.getDepartmentID();
                String NM = depgoin.getDepartmentName();
                String ManID = depgoin.getManagerID();
                String LocID = depgoin.getLocationID();

                String[] data = {ID, NM, ManID, LocID};
                dt.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan!\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldepartment = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_deparmentID = new javax.swing.JTextField();
        txt_departmentName = new javax.swing.JTextField();
        txt_managerID = new javax.swing.JTextField();
        txt_locationID = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabeldepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Department ID", "Department Name", "Manager ID", "Location ID"
            }
        ));
        tabeldepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldepartmentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldepartment);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DEPARTMENTS");

        jLabel2.setText("Department ID");

        jLabel3.setText("Department Name");

        jLabel4.setText("Manager ID");

        jLabel5.setText("Location ID");

        txt_deparmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deparmentIDActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)
                        .addGap(18, 18, 18)
                        .addComponent(btn_insert))
                    .addComponent(txt_deparmentID)
                    .addComponent(txt_departmentName)
                    .addComponent(txt_managerID)
                    .addComponent(txt_locationID, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btn_refresh)
                        .addGap(44, 44, 44)
                        .addComponent(btn_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_search)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_refresh)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(txt_deparmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_departmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_managerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_locationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update)
                            .addComponent(btn_delete)
                            .addComponent(btn_insert))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        DbConnection connection = new DbConnection();
        IDepartmentsControllers idc = new DepartmentsControllers(connection.getConnection());
        Department departments = new Department(txt_deparmentID.getText(), txt_departmentName.getText(), txt_managerID.getText(), 
                txt_locationID.getText());
        JOptionPane.showMessageDialog(null, idc.insert(departments));
        showtable();
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        DbConnection connection = new DbConnection();
        IDepartmentsControllers idc = new DepartmentsControllers(connection.getConnection());
        Department departments = new Department(txt_deparmentID.getText(), txt_departmentName.getText(), txt_managerID.getText(),
                txt_locationID.getText());
        idc.update(departments);
        showtable();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        DbConnection connection = new DbConnection();
        IDepartmentsControllers idc = new DepartmentsControllers(connection.getConnection());
        Department departments = new Department(txt_deparmentID.getText(), txt_departmentName.getText(), txt_managerID.getText(),
                txt_locationID.getText());
        idc.delete(departments.getDepartmentID());
        showtable();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       searching();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_deparmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deparmentIDActionPerformed
       DbConnection connection = new DbConnection();
       IDepartmentsControllers idc = new DepartmentsControllers(connection.getConnection());
    }//GEN-LAST:event_txt_deparmentIDActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        showtable();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void tabeldepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldepartmentMouseClicked
        DbConnection connection = new DbConnection();
        IDepartmentDao idepdao = new DepartmentDao(connection.getConnection());
        IDepartmentsControllers idc = new DepartmentsControllers(connection.getConnection());
        JTable source = (JTable) evt.getSource();
        int i = tabeldepartment.getSelectedRow();
        TableModel model = tabeldepartment.getModel();
        txt_deparmentID.setEditable(false);

        txt_deparmentID.setText(source.getModel().getValueAt(i, 0)+"");
        txt_departmentName.setText(source.getModel().getValueAt(i, 1)+"");
        txt_managerID.setText(source.getModel().getValueAt(i, 2)+"");
        txt_locationID.setText(source.getModel().getValueAt(i, 3)+"");
    }//GEN-LAST:event_tabeldepartmentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabeldepartment;
    private javax.swing.JTextField txt_deparmentID;
    private javax.swing.JTextField txt_departmentName;
    private javax.swing.JTextField txt_locationID;
    private javax.swing.JTextField txt_managerID;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
